INVERTER 32nm CMOS
- Tabela comparativa R^2, RMSE, MSE

INVERTER 7nm FINFET
- Tabela comparativa R^2, RMSE, MSE

In [1]:
import pandas as pd

path = "../../../../../outputs/CMOS/32nm/NOT/MLP_Regressor/results_mlps_20260527_095601.csv"

df = pd.read_csv(path)

# Show only 4 decimal places
# df = df.round(4)

- DT: Decisicion Tree
- RF: Random Forest
- MLP-S-SKL: Scikit-Learn Single Output
- MLP-M-SKL: Scikit-Learn	Multi-output
-MLP-S-K: Keras Single Output
- MLP-M-K: Keras Multi-output

### DF & RF Result Tables

In [2]:
data = {
    'r2':   [0.9996, 0.9995, 0.9995, 0.9997, 0.9996, 0.9983],
    'rmse': [0.0038, 0.0035, 0.0135, 0.0032, 0.0028, 0.0106],
}

index = pd.MultiIndex.from_tuples([
    ('DT', 'tphl'),
    ('DT', 'tphl'),
    ('DT', 'corrent'),
    ('RF', 'tphl'),
    ('RF', 'tphl'),
    ('RF', 'corrent'),

], names=['model', 'target'])

df_G = pd.DataFrame(data, index=index)
df_G.T

model       DT                      RF
target    tphl    tphl corrent    tphl    tphl corrent
r2      0.9996  0.9995  0.9995  0.9997  0.9996  0.9983
rmse    0.0038  0.0035  0.0135  0.0032  0.0028  0.0106

# INVERTER 32nm CMOS

## All Results

In [3]:
df_invertido = df.T
df_invertido

            mlp_S_SKL                                                    \
                 tphl      tphl      tplh      tplh   corrent   corrent
target_name       val      test       val      test       val      test
r2           0.999675  0.999657  0.999273  0.999269  0.998177  0.998194
rmse         0.018046  0.018645  0.026609  0.027004  0.042669  0.042582
mse          0.000326  0.000348  0.000708  0.000729  0.001821  0.001813

            mlp_M_SKL             mlp_S_K                       mlp_M_K
                  all       all      tphl      tplh   corrent       all
target_name       val      test       val       val       val       val
r2           0.998644  0.998632  0.999899  0.998904  0.996783  0.997096
rmse          0.03502  0.035425  0.010087  0.032674  0.056678  0.053191
mse          0.001348  0.001373  0.000102  0.001068  0.003212  0.002886

## Validation Results

In [4]:
# Results validation set
df_val = df[df['target_name'].str.endswith('val')].copy()
df_val.T

            mlp_S_SKL                     mlp_M_SKL   mlp_S_K            \
                 tphl      tplh   corrent       all      tphl      tplh
target_name       val       val       val       val       val       val
r2           0.999675  0.999273  0.998177  0.998644  0.999899  0.998904
rmse         0.018046  0.026609  0.042669   0.03502  0.010087  0.032674
mse          0.000326  0.000708  0.001821  0.001348  0.000102  0.001068

                        mlp_M_K
              corrent       all
target_name       val       val
r2           0.996783  0.997096
rmse         0.056678  0.053191
mse          0.003212  0.002886

In [5]:
# Save in figures/32nm_cmos/03_results/

## Test Results

In [6]:
# Results test set
df_test = df[df['target_name'].str.endswith('test')].copy()
df_test.T

            mlp_S_SKL                     mlp_M_SKL
                 tphl      tplh   corrent       all
target_name      test      test      test      test
r2           0.999657  0.999269  0.998194  0.998632
rmse         0.018645  0.027004  0.042582  0.035425
mse          0.000348  0.000729  0.001813  0.001373

In [7]:
# Save in figures/32nm_cmos/03_results/