# INVERTER CIRCUIT 32nm bulk CMOS

> Dataset source repository: https://github.com/GabriellJacinto/Electrical-Behaviour-Prediction
> Dataset Path: Electrical-Behaviour-Prediction/CMOS/32nm/NOT/Models/simu0/Advanced_Algorithms.ipynb

<small>

I'm using simu_0/treated_data dataset in this analysis

**Joined_data.csv:** contém os resultados brutos das simulações elétricas feitas no hspice (Monte Carlo).

**Treated_data.csv:** contém widths, tensões e temperaturas mapeadas.

O notebook advanced_algorithms usa o joined_data e depois gera o treated_data.

*No entanto, ainda não descobri a diferença entre simulação0 e simulação1. Estou usando a simul0.*

</small>

# Evaluation and Results

Metrics
- R² score (coefficient of determination) regression score function
- RMSE and MSE error metrics

In [27]:
import pandas as pd

path = "/home/eduarda/Repos/jupyter_ic/outputs/CMOS/32nm/NOT/MLP_Regressor/SKL/single_output/results_singleout_mlps_20260531_175251.csv"

df = pd.read_csv(path)

# Show only 4 decimal places
# df = df.round(4)

In [28]:
## All Results

In [29]:
df_invertido = df.T
df_invertido

            mlp_S_SKL
                 tphl      tphl      tplh      tplh    energy    energy
target_name       val      test       val      test       val      test
r2           0.999675  0.999657  0.999273  0.999269  0.998177  0.998194
rmse         0.018046  0.018645  0.026609  0.027004  0.042669  0.042582
mse          0.000326  0.000348  0.000708  0.000729  0.001821  0.001813

## Validation Results

In [30]:
# Results validation set
df_val = df[df['target_name'].str.endswith('val')].copy()
df_val.T

            mlp_S_SKL
                 tphl      tplh    energy
target_name       val       val       val
r2           0.999675  0.999273  0.998177
rmse         0.018046  0.026609  0.042669
mse          0.000326  0.000708  0.001821

## Test Results

In [31]:
# Results test set
df_test = df[df['target_name'].str.endswith('test')].copy()
df_test.T

            mlp_S_SKL
                 tphl      tplh    energy
target_name      test      test      test
r2           0.999657  0.999269  0.998194
rmse         0.018645  0.027004  0.042582
mse          0.000348  0.000729  0.001813

### DF & RF Result Tables

In [32]:
data = {
    'r2':   [0.9996, 0.9995, 0.9995, 0.9997, 0.9996, 0.9983],
    'rmse': [0.0038, 0.0035, 0.0135, 0.0032, 0.0028, 0.0106],
}

index = pd.MultiIndex.from_tuples([
    ('DT', 'tphl'),
    ('DT', 'tphl'),
    ('DT', 'corrent'),
    ('RF', 'tphl'),
    ('RF', 'tphl'),
    ('RF', 'corrent'),

], names=['model', 'target'])

df_G = pd.DataFrame(data, index=index)
df_G.T

model       DT                      RF
target    tphl    tphl corrent    tphl    tphl corrent
r2      0.9996  0.9995  0.9995  0.9997  0.9996  0.9983
rmse    0.0038  0.0035  0.0135  0.0032  0.0028  0.0106