INVERTER 32nm CMOS
- Tabela comparativa R^2, RMSE, MSE

INVERTER 7nm FINFET
- Tabela comparativa R^2, RMSE, MSE

In [1]:
import pandas as pd

path = "../outputs/not_32nm_cmos/results_mlps"

df = pd.read_csv(path)

# Show only 4 decimal places
df = df.round(4)

- DT: Decisicion Tree
- RF: Random Forest
- MLP-S-SKL: Scikit-Learn Single Output
- MLP-M-SKL: Scikit-Learn	Multi-output
-MLP-S-K: Keras Single Output
- MLP-M-K: Keras Multi-output

### DF & RF Result Tables

In [2]:
data = {
    'r2':   [0.9996, 0.9995, 0.9995, 0.9997, 0.9996, 0.9983],
    'rmse': [0.0038, 0.0035, 0.0135, 0.0032, 0.0028, 0.0106],
}

index = pd.MultiIndex.from_tuples([
    ('DT', 'tphl'),
    ('DT', 'tphl'),
    ('DT', 'corrent'),
    ('RF', 'tphl'),
    ('RF', 'tphl'),
    ('RF', 'corrent'),

], names=['model', 'target'])

df_G = pd.DataFrame(data, index=index)
df_G.T

model       DT                      RF
target    tphl    tphl corrent    tphl    tphl corrent
r2      0.9996  0.9995  0.9995  0.9997  0.9996  0.9983
rmse    0.0038  0.0035  0.0135  0.0032  0.0028  0.0106

# INVERTER 32nm CMOS

## All Results

In [3]:
df_invertido = df.T
df_invertido

            mlp_S_SKL                                         mlp_M_SKL  \
                 tphl    tphl    tplh    tplh corrent corrent       all
target_name       val    test     val    test     val    test       val
r2             0.9997  0.9996  0.9993  0.9993  0.9981  0.9981    0.9986
rmse           0.0186   0.019  0.0265  0.0269  0.0436  0.0435     0.036
mse            0.0003  0.0004  0.0007  0.0007  0.0019  0.0019    0.0014

                    mlp_S_K                 mlp_M_K
                all    tphl    tplh corrent     all
target_name    test     val     val     val     val
r2           0.9986  0.9999  0.9988  0.9962   0.997
rmse         0.0364  0.0098  0.0339  0.0618  0.0541
mse          0.0014  0.0001  0.0011  0.0038   0.003

## Validation Results

In [4]:
# Results validation set
df_val = df[df['target_name'].str.endswith('val')].copy()
df_val

                  target_name      r2    rmse     mse
mlp_S_SKL tphl            val  0.9997  0.0186  0.0003
          tplh            val  0.9993  0.0265  0.0007
          corrent         val  0.9981  0.0436  0.0019
mlp_M_SKL all             val  0.9986  0.0360  0.0014
mlp_S_K   tphl            val  0.9999  0.0098  0.0001
          tplh            val  0.9988  0.0339  0.0011
          corrent         val  0.9962  0.0618  0.0038
mlp_M_K   all             val  0.9970  0.0541  0.0030

In [5]:
# Save in figures/32nm_cmos/03_results/

## Test Results

In [6]:
# Results test set
df_test = df[df['target_name'].str.endswith('test')].copy()
df_test.T

            mlp_S_SKL                 mlp_M_SKL
                 tphl    tplh corrent       all
target_name      test    test    test      test
r2             0.9996  0.9993  0.9981    0.9986
rmse            0.019  0.0269  0.0435    0.0364
mse            0.0004  0.0007  0.0019    0.0014

In [7]:
# Save in figures/32nm_cmos/03_results/