INVERTER 32nm CMOS
- Tabela comparativa R^2, RMSE, MSE

INVERTER 7nm FINFET
- Tabela comparativa R^2, RMSE, MSE

In [1]:
import pandas as pd

path = "../outputs/not_32nm_cmos/results_mlps"

df = pd.read_csv(path)

In [2]:
# Results validation set
df_val = df[df['target_name'].str.endswith('val')].copy()

df_val

                  target_name        r2      rmse       mse
mlp_S_SKL tphl            val  0.995513  0.067093  0.004501
          tplh            val  0.996147  0.061261  0.003753
          corrent         val  0.993025  0.083461  0.006966
mlp_M_SKL all             val  0.994229  0.074693  0.005734
mlp_S_K   tphl            val  0.998847  0.034011  0.001157
          tplh            val  0.999017  0.030944  0.000958
          corrent         val  0.996936  0.055321  0.003060
mlp_M_K   all             val  0.995104  0.069055  0.004858

In [3]:
# Results test set
df_test = df[df['target_name'].str.endswith('test')].copy()

df_test

                  target_name        r2      rmse       mse
mlp_S_SKL tphl           test  0.995431  0.068030  0.004628
          tplh           test  0.996073  0.062579  0.003916
          corrent        test  0.993060  0.083467  0.006967
mlp_M_SKL all            test  0.994183  0.075527  0.005844

## Validation Results MLP Using SKL e Keras 32nm not cmos

In [9]:
df_invertido = df_val.T
df_invertido

            mlp_S_SKL                     mlp_M_SKL   mlp_S_K            \
                 tphl      tplh   corrent       all      tphl      tplh
target_name       val       val       val       val       val       val
r2           0.995513  0.996147  0.993025  0.994229  0.998847  0.999017
rmse         0.067093  0.061261  0.083461  0.074693  0.034011  0.030944
mse          0.004501  0.003753  0.006966  0.005734  0.001157  0.000958
clean_name        val       val       val       val       val       val

                        mlp_M_K
              corrent       all
target_name       val       val
r2           0.996936  0.995104
rmse         0.055321  0.069055
mse           0.00306  0.004858
clean_name        val       val

KeyError: 1